services:
  - type: web
    name: ctfd
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn serve:app
    region: oregon
    plan: free
    runtime: python
    autoDeploy: true
